Esu 1466 honeypot pipeline
ndlib/dec-blueprints pull request #11
Opened 2020-12-09 16:24 UTC by wsill

2020-12-10 15:58 UTC, ialford requested changes
I think there's a few things to clean up. Has this been deployed, and if so have you ran any thing against the deployed services to be sure they are acting correctly?

2020-12-10 15:58 UTC, ialford commented on src/honeypot/honeypot-pipeline.ts
> +    ],
These should be scoped down a little - as it is, this could impact non-DEC services

2020-12-10 15:58 UTC, ialford commented on src/honeypot/honeypot-stack.ts
> +    }
Instead of doing this, you should look at the `asset-helpers` and leverage that, similar to https://github.com/ndlib/dec-blueprints/blob/main/src/buzz/buzz-stack.ts#L59 or https://github.com/ndlib/dec-blueprints/blob/main/src/honeycomb/rails-construct.ts#L106

2020-12-10 15:58 UTC, ialford commented on test/honeypot/honeypot-pipeline.test.ts
> +    const honeypotContext = getContextByNamespace('hneypot')
```suggestion
    const honeypotContext = getContextByNamespace('honeypot')
```

Not sure if this typo impacts your tests - if you fix, be sure to re-run

2020-12-10 15:58 UTC, ialford commented on test/honeypot/honeypot-stack.test.ts
> +import { getContextByNamespace } from '../../lib/context-helpers'
These should all reference the `src` path.

2020-12-10 16:20 UTC, wsill commented on src/honeypot/honeypot-pipeline.ts
> +    ],
There is so much truncation that adding a few characters for a test (i.e, using namespace ws-dec) would make it fail.  I can certainly add the "dec-" string back.

2021-01-19 16:47 UTC, ialford requested changes

2021-01-19 16:47 UTC, ialford commented on src/honeypot/honeypot-stack.ts
> +        'ssm:*',
I would scope this down to at least only include `ssm:Get*` to be sure there aren't unforeseen destructive actions.

2021-03-17 17:34 UTC, wsill commented
Okay, I believe I've gotten this all working.  I've also created testlibnd stacks for the entire process.  The code pipeline is viewable from https://console.aws.amazon.com/codesuite/codepipeline/pipelines/wsill-dec-honeypot-pipeline-DeploymentPipelineEDAF206A-DWWU0QLJNWVB/view?region=us-east-1

2021-04-29 15:05 UTC, closed without merging

2021-04-29 15:06 UTC, wsill commented
This is now in another request
https://github.com/ndlib/dec-blueprints/pull/18