feat: Add honeypot stack and reconcile pipeline
ndlib/dec-blueprints pull request #18
Opened 2021-04-29 15:02 UTC by wsill

This adds in the honeypot stack and reconciles the pipeline. There is a slight change in path and a honeypot folder was added to be consistent with buzz and honeycomb.

2021-04-29 17:09 UTC, hanstra reviewed
I see that each person is adding a set of credentials in Parameter Store. Will those be condensed into one set at some point?  I don't quite follow how the foundation stack is going to get normalized across all of the pieces of DEC.

2021-04-29 17:28 UTC, wsill commented
> I see that each person is adding a set of credentials in Parameter Store. Will those be condensed into one set at some point? I don't quite follow how the foundation stack is going to get normalized across all of the pieces of DEC.

I would assume there will be a single set for test and prod in each AWS environment.  I believe each person is adding a set so they can test their separate component of dec.

2021-05-03 13:10 UTC, jgondron requested changes

2021-05-03 17:27 UTC, ialford approved these changes

2021-05-03 18:12 UTC, jgondron approved these changes

2021-05-03 18:43 UTC, merged