Beehive pipe - all changes to have working pipeline in testlibnd
ndlib/dec-blueprints pull request #23
Opened 2021-06-09 14:24 UTC by hanstra

Currently deployed with th-dec prefix

2021-06-09 15:05 UTC, ialford requested changes
Some questions or suggestions throughout the review.

Also, we should settle on `npm` or `yarn` and delete the unnecessary lock file, although we can do that after a merge.

2021-06-09 15:05 UTC, ialford commented on src/beehive/beehive-pipeline.ts
> +        buildImage: codebuild.LinuxBuildImage.fromDockerRegistry('postman/newman', {
Specify a version of the Newman container, or use the DockerhubImage.fromNewman method in src/dockerhub-image.ts

2021-06-09 15:05 UTC, ialford commented on src/beehive/beehive-pipeline.ts
> +        buildImage: codebuild.LinuxBuildImage.fromDockerRegistry('postman/newman', {
Specify a version of the Newman container, or use the DockerhubImage.fromNewman method in src/dockerhub-image.ts

2021-06-09 15:05 UTC, ialford commented on src/beehive/beehive-stack.ts
>        new CnameRecord(this, 'BeehiveCNAME', { // eslint-disable-line no-new
Does this error when it's deploying a `library.nd.edu` domain (where there is no hosted zone?)

2021-06-09 15:06 UTC, jgondron requested changes
There are a few areas that need to be changed to better integrate with the way we're doing pipelines in this app now, but I'll take care of those when I integrate my changes. I just have a few changes that should probably be made now

2021-06-09 15:06 UTC, jgondron commented on src/beehive/beehive-stack.ts
>    public readonly cloudfront: CloudFrontWebDistribution
These don't appear to be used. Should remove them so that they're not required when creating the stack.
```suggestion
```

2021-06-09 15:07 UTC, jgondron commented on cdk.context.json
> +  "beehive:hostnamePrefix": "dec-collections",
No, this should be `collections`

2021-06-09 15:09 UTC, hanstra commented on cdk.context.json
> +  "beehive:hostnamePrefix": "dec-collections",
Somewhat lost in history, but I think I just wanted to make sure I did not somehow name the same thing as the current service.

2021-06-09 15:11 UTC, hanstra commented on bin/services.ts
> +import { BuzzStack } from '../src//buzz/buzz-stack'
Fixed

2021-06-09 15:15 UTC, hanstra commented on src/beehive/beehive-pipeline.ts
> +    const approvalAction = new ManualApprovalAction({
Change made and pushed

2021-06-09 15:20 UTC, hanstra commented on src/beehive/beehive-stack.ts
>    public readonly cloudfront: CloudFrontWebDistribution
Removed.

2021-06-09 15:23 UTC, hanstra commented on src/beehive/beehive-pipeline.ts
> +        buildImage: codebuild.LinuxBuildImage.fromDockerRegistry('postman/newman', {
Do you have a suggested version number?  When I go to Docker Registry site, there is a postman/newman container and I don't see any versioning options there.

2021-06-09 15:24 UTC, ialford commented on src/beehive/beehive-pipeline.ts
> +        buildImage: codebuild.LinuxBuildImage.fromDockerRegistry('postman/newman', {
```suggestion
        buildImage: codebuild.LinuxBuildImage.fromDockerRegistry('postman/newman:5', {
```

This should work as it matches what is in the DockerhubImage file.

2021-06-09 15:41 UTC, hanstra commented on src/beehive/beehive-pipeline.ts
> +        buildImage: codebuild.LinuxBuildImage.fromDockerRegistry('postman/newman', {
Thanks. Change has been made.

2021-06-09 15:41 UTC, hanstra commented on src/beehive/beehive-pipeline.ts
> +        buildImage: codebuild.LinuxBuildImage.fromDockerRegistry('postman/newman', {
Is this also covered with the specific version of container?

2021-06-09 15:42 UTC, ialford commented on src/beehive/beehive-pipeline.ts
> +        buildImage: codebuild.LinuxBuildImage.fromDockerRegistry('postman/newman', {
You should use the same version in both places, whatever you pushed up.

2021-06-10 15:54 UTC, hanstra commented on cdk.context.json
> +  "beehive:hostnamePrefix": "dec-collections",
Right now, it is still dec-collections. Do we want to change?

2021-06-10 15:55 UTC, ialford commented on cdk.context.json
> +  "beehive:hostnamePrefix": "dec-collections",
I think there's no reason not to change it. Until `collections.library.nd.edu` DNS is moved, this won't impact the running service in VMWare.

2021-06-10 19:32 UTC, jgondron commented on src/beehive/beehive-stack.ts
>        new CnameRecord(this, 'BeehiveCNAME', { // eslint-disable-line no-new
It should skip this in libnd, since env.createDns will be false there

2021-06-10 19:38 UTC, ialford commented on src/beehive/beehive-stack.ts
>        new CnameRecord(this, 'BeehiveCNAME', { // eslint-disable-line no-new
I think I'm just not seeing the conditional?

2021-06-10 19:45 UTC, jgondron commented on src/beehive/beehive-stack.ts
>        new CnameRecord(this, 'BeehiveCNAME', { // eslint-disable-line no-new
Yeah, because it was a line that wasn't changed as part of this PR. Expand the lines above this and you should see it

2021-06-10 19:46 UTC, ialford commented on src/beehive/beehive-stack.ts
>        new CnameRecord(this, 'BeehiveCNAME', { // eslint-disable-line no-new
Found it, thanks.

2021-06-11 17:54 UTC, jgondron approved these changes

2021-06-11 17:57 UTC, ialford approved these changes

2021-06-11 18:15 UTC, merged