WIP - ESU-1467 Beehive CDK
ndlib/dec-blueprints pull request #3
Opened 2020-10-09 20:24 UTC by ialford

2020-10-20 13:54 UTC, mlkirkpatrick approved these changes

2020-10-20 13:54 UTC, mlkirkpatrick commented on cdk.context.json
> +  "beehive:hostnamePrefix": "collections-dev",
This doesn't seem right to me since you would end up with `collections-dev` even when deploying to libnd unless you specifically remember to override this. It also wouldn't work well in a pipeline where you have to deploy multiple stages (test and prod.)

I feel like env and/or stage should be used to concatenate the hostname as needed.

2020-10-20 13:54 UTC, mlkirkpatrick commented on src/beehive-stack.ts
> +      const record = new CnameRecord(this, 'BeehiveCNAME', { // I added this const to fix a linting error of "Do not use 'new' for side effects."
If you're sure the code is proper despite a linting violation, use `// eslint-disable-line <rule-name>` instead.

There's also `eslint-disable-next-line` in case the line with the violation is a bit long, so you can place the comment above the infringing line.

2020-10-20 14:32 UTC, ialford commented on cdk.context.json
> +  "beehive:hostnamePrefix": "collections-dev",
Agreed. I thought this was how other projects were doing it, but I must've been looking at, well, ¯\\_(ツ)_/¯

2020-10-20 14:32 UTC, ialford commented on src/beehive-stack.ts
> +      const record = new CnameRecord(this, 'BeehiveCNAME', { // I added this const to fix a linting error of "Do not use 'new' for side effects."
Disabled via inline comment

2020-10-20 14:36 UTC, ialford commented on test/beehive-stack.test.ts
> +    Resources: {
I agree in some ways, and am not sure in others. At the end of the day, we care about two things:

1.  that each small bit is doing something that we expect it to (as you mentioned, the "important things to test"

1. That the created CFN template is idempotent, which is more important in CI

As I'm thinking more about CI for CDK apps, I think we may need *both* - knowing that the full template test is going to have to be changed on deliberate updates. I certainly think there's room for discussion.

2020-10-20 17:50 UTC, jgondron commented on test/beehive-stack.test.ts
> +    Resources: {
If I may add a few things:
- People who understand cloudformation can review what it will generate, after all the cdk magic happens.
- We've already had occasions where cdk version changes have made changes to the synth'd template that we did not expect (ex: an export suddenly disappeared and everything failed). Seeing that change as part of the review removes these surprises.
- Not a fan of snapshot tests (think `matchTemplate` vs to`haveResource` https://docs.aws.amazon.com/cdk/latest/guide/testing.html). I'd prefer unit-ish tests that test the important expectations using haveResource with some subset of properties. The nature of these templates and the matcher capabilities can make this challenging, though, so at times you end up just having to matchTemplate, but I'd prefer using a complete snapshot match as a last resort.

2020-10-20 19:43 UTC, jgondron requested changes

2020-10-20 19:43 UTC, jgondron commented on bin/services.ts
> +    domainStackName: env.domainStackName,
Whatever stacks we pass the env object to can just get these properties directly from the env object. No reason to slice it up again as props

2020-10-20 19:43 UTC, jgondron commented on bin/services.ts
> +    domainName: env.domainName,
Similar comment to above

2020-10-20 19:43 UTC, jgondron commented on src/beehive-stack.ts
> +        names: [props.hostnamePrefix + '.' + cdk.Fn.importValue(`${props.domainStackName}:DomainName`)],
This has the opportunity to be different from the exposed this.hostname

2020-10-20 19:43 UTC, jgondron commented on src/beehive-stack.ts
> +          defaultTtl: (props.env === 'dev') ? cdk.Duration.seconds(0) : cdk.Duration.days(1),
props.env will be an object, not a string. Afaik this will always resolve to be false, making the duration 1 day even if in dev? This seems like a copy/paste from a different project, so if you want this to function similarly here, you probably want to check the props.env.name === 'dev'

2020-10-20 19:58 UTC, ialford commented on src/beehive-stack.ts
> +        names: [props.hostnamePrefix + '.' + cdk.Fn.importValue(`${props.domainStackName}:DomainName`)],
It does, but is that an issue? If it is, It should probably be an update to the definition of `this.hostname` rather than a change at this alias, which is taking a prefix and then appending the actual domain to the end to create (hopefully) a known-good FQDN. Thoughts?

2020-10-20 20:14 UTC, jgondron commented on src/beehive-stack.ts
> +        names: [props.hostnamePrefix + '.' + cdk.Fn.importValue(`${props.domainStackName}:DomainName`)],
Seems like you'd want this instead:
```suggestion
        names: [this.hostname + '.' + cdk.Fn.importValue(`${props.domainStackName}:DomainName`)],
```

2020-10-20 20:17 UTC, ialford commented on bin/services.ts
> +    domainStackName: env.domainStackName,
I'm struggling with this one. Would it be done within the stack files? How to I ensure that the array from `env` gets there to expose the properties?

2020-10-20 20:39 UTC, ialford commented on src/beehive-stack.ts
> +        names: [props.hostnamePrefix + '.' + cdk.Fn.importValue(`${props.domainStackName}:DomainName`)],
Updated

2020-10-20 21:34 UTC, ialford commented on src/beehive-stack.ts
> +          defaultTtl: (props.env === 'dev') ? cdk.Duration.seconds(0) : cdk.Duration.days(1),
Resolved

2020-10-20 21:35 UTC, ialford commented on bin/services.ts
> +    domainName: env.domainName,
Fixed

2020-10-20 21:35 UTC, ialford commented on bin/services.ts
> +    domainStackName: env.domainStackName,
Figured it out

2020-10-20 21:36 UTC, ialford commented on test/beehive-stack.test.ts
> +    Resources: {
Would like to get feedback on the tests in `test/foundation-stack.test.ts` from @mlkirkpatrick and @jgondron

2020-10-21 17:27 UTC, jgondron requested changes

2020-10-21 18:24 UTC, ialford commented on bin/services.ts
>      useExistingDnsZone: env.useExistingDnsZone,
updated

2020-10-21 18:37 UTC, mlkirkpatrick commented on test/beehive-stack.test.ts
> +    Resources: {
Looks good to me. I don't have anything to add.

2020-10-21 20:28 UTC, merged