Add SSL Cert to foundation and use it for CloudFront
ndlib/dec-blueprints pull request #4
Opened 2020-10-12 16:02 UTC by ialford

2020-10-12 16:04 UTC, mlkirkpatrick approved these changes

2020-10-12 16:04 UTC, mlkirkpatrick commented on cdk.context.json
>        "domainName": "libraries.nd.edu",
Is domainName still needed? Wouldn't you import this from the domainStack's exports?

2020-10-12 16:40 UTC, rdoughty approved these changes

2020-10-12 17:10 UTC, SteveMattison approved these changes

2020-10-12 18:14 UTC, jgondron requested changes

2020-10-12 18:14 UTC, jgondron commented on src/foundation-stack.ts
> +  readonly domainStack: string;
Would rather this be called `domainStackName`. `domainStack` gives the impression its type is a Stack, meaning it's created by this app.

2020-10-12 18:15 UTC, jgondron commented on cdk.context.json
>        "domainName": "libraries.nd.edu",
Second this

2020-10-12 18:31 UTC, ialford commented on cdk.context.json
>        "domainName": "libraries.nd.edu",
Should I just get rid of this context value then, and we can import as needed within the stacks?

2020-10-13 17:44 UTC, ialford commented on cdk.context.json
>        "domainName": "libraries.nd.edu",
@jgondron and @mlkirkpatrick - see my question above. Thoughts?

2020-10-13 17:47 UTC, mlkirkpatrick commented on cdk.context.json
>        "domainName": "libraries.nd.edu",
Yes, I think so.

2020-10-13 19:08 UTC, ialford commented on src/foundation-stack.ts
> +  readonly domainStack: string;
Updated

2020-10-15 17:44 UTC, jgondron approved these changes

2020-10-15 18:02 UTC, merged