Esu 1456 cdk code honeypot
ndlib/dec-blueprints pull request #6
Opened 2020-10-30 16:35 UTC by wsill

2020-11-02 14:15 UTC, ialford requested changes
I would look at taking the `networkStackName` out of each env, and move it up one level to apply to all stacks, although I'm happy to discuss if there's a feeling that it should live in the `env` blob. We should also write unit tests to ensure that the expected components are being created.

2020-11-02 14:15 UTC, ialford commented on cdk.context.json
> +      "networkStackName": "peered-network",
I thought we were using unpeered-network for the stacks?

2020-11-03 13:56 UTC, ialford commented
@wsill - I think everything is ok, but we still need some unit tests. Include testing of the  DNS Record creation based on the parameter, testing the proper hostname that gets created. Ensuring that each component part is created (ALB with proper listeners, ECS Service, etc) would be good to do as well, but testing anywhere there is a branch in logic based on an input should definitely have a test.

2020-11-03 13:58 UTC, wsill commented
> I would look at taking the `networkStackName` out of each env, and move it up one level to apply to all stacks, although I'm happy to discuss if there's a feeling that it should live in the `env` blob. We should also write unit tests to ensure that the expected components are being created.

I replaced useVpcId with networkStackName since you can get the vpcId by importing using  cdk.Fn.importValue(`${props.env.networkStackName}:VPCID`)  Since useVpcId was in each env do you still think it should move it up one level?

I had to hold off on unit test (only works locally) since it requires the honeypot repository directory.  I figured I would add a test once there is a cdk pipeline deploy code to pull down the honeypot repository directory.

2020-11-03 14:06 UTC, ialford commented
> > I would look at taking the `networkStackName` out of each env, and move it up one level to apply to all stacks, although I'm happy to discuss if there's a feeling that it should live in the `env` blob. We should also write unit tests to ensure that the expected components are being created.
> 
> I replaced useVpcId with networkStackName since you can get the vpcId by importing using cdk.Fn.importValue(`${props.env.networkStackName}:VPCID`) Since useVpcId was in each env do you still think I should move it up one level?
> 
> I had to hold off on unit test (only works locally) since it requires the honeypot repository directory. I figured I would add a test once there is a cdk pipeline deploy code to pull down the honeypot repository directory.

The `useVpcId` was in each env because we used a different VPC depending on the account we were in, and we were specifying those values. Now that we're using a known export value to fetch the VPC ID, I think that it could be moved out of `env` and just into the top-level context. Would still like to hear from someone else in @ndlib/esu regarding that.

The unit tests shouldn't be relying on another repository (such as the application code) - they should probably be reworked if they are relying on the app code. You should be looking primarily at testing the synthesized CloudFormation and ensuring it has the component parts that you were expecting.

2020-11-03 18:50 UTC, ialford commented
@wsill - try adding the below to `.github/workflows/ci.yml` after Line 21 - this should checkout the Honeypot code to allow the synth to complete.

```
    - name: Checkout Honeypot repo
      uses: actions/checkout@v2
      with:
        repository: ndlib/honeypot
        path: honeypot
```

2020-11-03 19:02 UTC, ialford commented on .github/workflows/ci.yml
>      - uses: actions/checkout@v2
Overall should look like this:
```
    steps:
    - uses: actions/checkout@v2
    - name: Checkout Honeypot repo
      uses: actions/checkout@v2
      with:
        repository: ndlib/honeypot
        path: honeypot
```

This should ensure the repositories are cloned and nested in the correct order.

2020-11-03 19:10 UTC, ialford commented on .github/workflows/ci.yml
> +    - uses: actions/checkout@v2
```suggestion
```

2020-11-03 19:37 UTC, ialford commented on src/honeypot-stack.ts
> +      directory: 'honeypot',
I don't think this will work when it gets into the deployment pipeline.

2020-11-03 20:10 UTC, ialford approved these changes

2020-11-06 22:06 UTC, jgondron requested changes

2020-11-06 22:06 UTC, jgondron commented on src/honeypot-stack.ts
> +      this.hostname = `${props.hostnamePrefix || this.stackName}` + `-${props.env.name}`
Would prefer not to use the env name here. Env in this case means account environment as opposed to stage. Ie will be 'dev' when we're deploying to testlibnd and 'prod' when deploying to libnd. So it's just going to add '-dev' to hostnames when in testlibnd.

2020-11-06 22:06 UTC, jgondron commented on src/honeypot-stack.ts
> +        RAILS_RUN_ENV: stringHelper('HoneypotService', 'rails_run_env'),
Just use a constant literal here of 'production'. Our test stack will still want to run like it is production.

2020-11-12 15:18 UTC, jgondron commented on src/honeypot-stack.ts
> +        parameterName: `/all/${props.hostnamePrefix}/${key}`,
I'd probably just use stack name here since that will contain both the service name and the stage such as 'honeypot-prod' and 'honeypot-test'. If you accept this, you should also change the readme to match.
```suggestion
        parameterName: `/all/${this.stackName}/${key}`,
```

2020-11-12 15:19 UTC, jgondron approved these changes

2020-11-12 16:21 UTC, merged