Esu 1469 buzz to cdk
ndlib/dec-blueprints pull request #7
Opened 2020-11-13 14:06 UTC by ialford

The rework of Buzz's CloudFormation to CDK. There's probably a bit of optimization that could take place here, but want to get it out for review now that Bill's honeypot code is merged.

2020-11-13 21:30 UTC, jrittenh approved these changes

2020-11-16 14:41 UTC, wsill commented on src/buzz-stack.ts
> +        parameterName: `/all/${props.hostnamePrefix}/production/${key}`,
Should we be using the following which is what JG recommended for the code I submitted and merged into master?
parameterName: `/all/${this.stackName}/${key}`,

2020-11-16 14:42 UTC, jgondron requested changes

2020-11-16 14:42 UTC, jgondron commented on src/buzz-stack.ts
> +  readonly foundationStack: FoundationStack,
foundationStack is already declared in SharedServiceStackProps

2020-11-16 14:42 UTC, jgondron commented on src/buzz-stack.ts
> +  public readonly hostname: string
Remove this, appears to be unused

2020-11-16 14:42 UTC, jgondron commented on cdk.context.json
> +  "buzz:networkStackName": "peered-network",
This should be part of the CustomEnvironment pulled in already

2020-11-16 14:42 UTC, jgondron commented on cdk.context.json
> +  "networkStackName": "unpeered-network",
This should be part of the CustomEnvironment pulled in already

2020-11-16 14:42 UTC, jgondron commented on src/buzz-stack.ts
> +        cdk.Fn.sub(`arn:aws:ssm:${this.region}:${this.account}:parameter/all/${props.hostnamePrefix}/*`),
There's a few other places where this occurs in this PR, but are you sure you want to use hostname prefix as the path? Our convention usually includes the service and stage name such as `buzz-test` and `buzz-prod`, which you can likely get with the stack name. Using hostname you'll get `buzz` and `buzz-test`.

2020-11-16 15:04 UTC, ialford commented on src/buzz-stack.ts
> +        cdk.Fn.sub(`arn:aws:ssm:${this.region}:${this.account}:parameter/all/${props.hostnamePrefix}/*`),
Part of the problem here is that Buzz already had paths set up for the CloudFormation implementation, and I was trying to avoid duplicating SSM values. I am fine with changing the pattern - but I then want us to go back and do some data hygiene on the SSM values that are no longer going to be necessary.

2020-11-16 15:04 UTC, ialford commented on src/buzz-stack.ts
> +        parameterName: `/all/${props.hostnamePrefix}/production/${key}`,
See https://github.com/ndlib/dec-blueprints/pull/7#discussion_r524334633

2020-11-16 15:23 UTC, ialford commented on src/buzz-stack.ts
> +  readonly foundationStack: FoundationStack,
It is, but I'm struggling with how to be able to refer to it. Additionally, other services we've written have followed this pattern, including [MARBLE](https://github.com/ndlib/marble-blueprints/blob/master/deploy/cdk/lib/static-host/static-host-stack.ts#L20) and [DEC](https://github.com/ndlib/dec-blueprints/blob/main/src/honeypot-stack.ts#L17) itself. 

Have you had success with not having `foundationStack` on your Honeycomb stacks, @jgondron ?

2020-11-16 15:25 UTC, ialford commented on src/buzz-stack.ts
> +  readonly foundationStack: FoundationStack,
The main issue is that `foundationStack` is an optional prop in `SharedServiceStackProps`, I believe.

2020-11-16 15:28 UTC, ialford commented on cdk.context.json
> +  "networkStackName": "unpeered-network",
removed

2020-11-16 15:28 UTC, ialford commented on cdk.context.json
> +  "buzz:networkStackName": "peered-network",
removed

2020-11-16 15:58 UTC, wsill commented on src/buzz-stack.ts
> +        cdk.Fn.sub(`arn:aws:ssm:${this.region}:${this.account}:parameter/all/${props.hostnamePrefix}/*`),
I don't see any /all/dec-buzz/ paths?  Isn't dec-buzz the value for the ${this.stackName} string?

2020-11-16 16:04 UTC, ialford commented on src/buzz-stack.ts
> +        cdk.Fn.sub(`arn:aws:ssm:${this.region}:${this.account}:parameter/all/${props.hostnamePrefix}/*`),
It would be, but I'm not currently using `this.stackName` because Buzz was already set up for CloudFormation - using a different pathing pattern. 

Current pattern is `/all/buzz/${prep/production}/${key}` and I will need to recreate all the values using `buzz-test` or `dec-buzz-test` and `buzz-prod` or `dec-buzz-prod` depending.

2020-11-16 18:46 UTC, ialford commented on src/buzz-stack.ts
> +  readonly foundationStack: FoundationStack,
OK, so the more I am thinking about it, the more I think it is the optional part that is the problem here. A FoundationStack isn't an optional prop for buzz-stack, as it absolutely needs the things it is providing here (the VPC information and the Cert ARN). Does it make more sense to remove the optionality of `foundationStack` in `SharedServiceStackProps` or to include it as non-optional in `buzz-stack.ts`? 

Both would work, but I think it's important to make the FoundationStack non-optional via one of these two means. @ndlib/esu any thoughts?

2020-11-16 20:02 UTC, jgondron commented on src/buzz-stack.ts
> +  readonly foundationStack: FoundationStack,
Seems like they all require it so I'd just make it required.

On a related note, if I could ask you all to please be on the lookout for other props that are required by all and add them to SharedServiceStackProps instead of copy/pasting them everywhere. This was possibly a premature attempt at drying up the props a bit, so if in the end we only end up with one prop that's shared across all, it might not make sense to even have this SharedServiceStackProps interface.

2020-11-17 14:12 UTC, ialford commented on src/buzz-stack.ts
> +  readonly foundationStack: FoundationStack,
Made a required prop

2020-11-17 14:13 UTC, ialford commented on src/buzz-stack.ts
> +        cdk.Fn.sub(`arn:aws:ssm:${this.region}:${this.account}:parameter/all/${props.hostnamePrefix}/*`),
Fixed and created test SSMs to verify

2020-11-17 14:13 UTC, ialford commented on src/buzz-stack.ts
> +  public readonly hostname: string
removed

2020-11-17 14:13 UTC, ialford commented on src/buzz-stack.ts
> +        parameterName: `/all/${props.hostnamePrefix}/production/${key}`,
Fixed

2020-11-17 16:15 UTC, jgondron requested changes

2020-11-17 16:15 UTC, jgondron commented on src/buzz-stack.ts
> +    const databaseConnectSecurityGroupParam = StringParameter.valueFromLookup(this, '/all/buzz/sg_database_connect')
Is this going to be the same for both test and prod?

2020-11-17 16:20 UTC, ialford commented on src/buzz-stack.ts
> +    const databaseConnectSecurityGroupParam = StringParameter.valueFromLookup(this, '/all/buzz/sg_database_connect')
Yes - it's just the group that gives access to the DB host, and both DBs are on the same host

2020-11-17 16:45 UTC, jgondron approved these changes

2020-11-17 16:46 UTC, merged