WIP - buzz deployment cdk
ndlib/dec-blueprints pull request #8
Opened 2020-11-30 16:36 UTC by ialford

Please provide any feedback on the code that you have. 

I am currently working on unit tests for the pipeline stack, and will remove the WIP label when those are stable. However, I think it's important to start garnering feedback now.

2020-11-30 17:52 UTC, mlkirkpatrick approved these changes
See comments; approving since they are just suggestions and some minor cleanup.

There were a few more code style inconsistencies which I didn't point out, so you might want to just run `npm run format` to clean that all up. 😄

2020-11-30 17:52 UTC, mlkirkpatrick commented on cdk.context.json
> +  "infraSourceBranch": "ESU-1515-buzz-deployment-cdk",
Probably shouldn't change this in the context file. I'm guessing you forgot to set it back when checking in.

2020-11-30 17:52 UTC, mlkirkpatrick commented on src/buzz/buzz-pipeline.ts
> +        }),
We could avoid using docker here if you add an install phase with node runtime and
```npm install -g newman```

(for this step anyway. Might not be worth changing since we need it for the stack build regardless.)

2020-11-30 17:52 UTC, mlkirkpatrick commented on src/buzz/buzz-pipeline.ts
> +          }))
See above.

2020-11-30 17:52 UTC, mlkirkpatrick commented on src/buzz/buzz-pipeline.ts
> +          }))
Indentation got a little wonky here.

2020-11-30 17:52 UTC, mlkirkpatrick commented on src/buzz/buzz-pipeline.ts
> +          actions: [ migrateTest.action, deployTest.action, smokeTestsAction /* ,approvalAction*/ ],
Approval action commented out?

2020-11-30 17:52 UTC, mlkirkpatrick commented on src/buzz/buzz-pipeline.ts
> +    }))
I think these should be up in the addPermissions function to at least keep all of the permissions together.

2020-11-30 17:52 UTC, mlkirkpatrick commented on src/namespaced-policy.ts
> +export class NamespacedPolicy {
If we're going to be using this class in multiple projects I think it would be nice if we added it to ndlib-cdk. There's already an issue created for it: ndlib/ndlib-cdk#10

2020-11-30 17:53 UTC, ialford commented on cdk.context.json
> +  "infraSourceBranch": "ESU-1515-buzz-deployment-cdk",
Yep.

2020-11-30 18:04 UTC, SteveMattison approved these changes

2020-11-30 18:35 UTC, rdoughty approved these changes

2020-11-30 19:43 UTC, ialford commented on bin/services.ts
> +import { BuzzStack } from '../src//buzz/buzz-stack'
That is because I fat-fingered the path. Will fix.

2020-12-01 16:37 UTC, ialford commented on src/namespaced-policy.ts
> +export class NamespacedPolicy {
I agree. Would love for someone to pick up that issue.

2020-12-02 15:30 UTC, jrittenh approved these changes

2020-12-03 20:59 UTC, jgondron requested changes

2020-12-03 20:59 UTC, jgondron commented on src/buzz/buzz-pipeline.ts
> +    const artifactBucket = new Bucket(this, 'artifactBucket', {
We should probably use one bucket for all of the pipelines just to cut down on buckets in the accounts. Did something like this in marble by making foundation stack for the pipelines https://github.com/ndlib/marble-blueprints/blob/master/deploy/cdk/lib/foundation/pipeline-foundation-stack.ts then passing it to each pipeline through props https://github.com/ndlib/marble-blueprints/blob/master/deploy/cdk/lib/iiif-serverless/deployment-pipeline.ts#L249

2020-12-03 20:59 UTC, jgondron commented on src/buzz/buzz-pipeline.ts
> +        buildImage: LinuxBuildImage.fromDockerRegistry('postman/newman', {
Can you do something like what I did in marble: https://github.com/ndlib/marble-blueprints/blob/master/deploy/cdk/lib/dockerhub-image.ts? Just to cut down on the processing of credentials and creation of the build image.

2020-12-03 20:59 UTC, jgondron commented on src/cdk-pipeline-migrate.ts
> +
You don't need any of this do you? This project isn't really doing anything with cdk.

2020-12-03 20:59 UTC, jgondron commented on src/cdk-pipeline-migrate.ts
> +export class CDKPipelineMigrate extends Construct {
This isn't really a CDK thing. It's more a rails migration type action.
```suggestion
export class RailsMigration extends Construct {
```

I'm also still not convinced this is a good way to handle this, or that it will work for other pipelines without having to override nearly everything. I'd prefer we just reuse the image built from the previous stage, either by pulling it from whatever ECR/Tag was pushed by cdk in the previous stage, or by running an ECS task with command overrides using the task definition deployed in the previous stage.

2020-12-03 20:59 UTC, jgondron commented on src/honeypot-stack.ts
> +    if (!fs.existsSync(props.appDirectory)) {
Don't do this. Using the AssetHelpers should cover the missing asset problem

2020-12-03 20:59 UTC, jgondron commented on test/helpers.ts
> +export const mockDockerCredentials = (response?: any) => {
Did you have fun writing this? Let us know in the comments below.

2020-12-03 21:07 UTC, ialford commented on test/helpers.ts
> +export const mockDockerCredentials = (response?: any) => {
NARRATOR: He did not.

2020-12-04 15:20 UTC, ialford commented on src/buzz/buzz-pipeline.ts
> +        }),
We could - however we've been using this method for consistency in both the pipelines as well as being able to replicate the step locally with a `docker pull` of the relevant image, so I think I'll leave it for now.

2020-12-04 15:20 UTC, ialford commented on src/buzz/buzz-pipeline.ts
> +          actions: [ migrateTest.action, deployTest.action, smokeTestsAction /* ,approvalAction*/ ],
Reinstated.

2020-12-04 15:21 UTC, ialford commented on src/buzz/buzz-pipeline.ts
> +          }))
This is how `npm run format` wants it, so who am I to argue with standardx?

2020-12-04 15:21 UTC, ialford commented on src/buzz/buzz-pipeline.ts
> +    const artifactBucket = new Bucket(this, 'artifactBucket', {
Added shared artifact bucket to foundation stack

2020-12-04 15:21 UTC, ialford commented on src/buzz/buzz-pipeline.ts
> +        buildImage: LinuxBuildImage.fromDockerRegistry('postman/newman', {
Done

2020-12-04 15:22 UTC, ialford commented on src/cdk-pipeline-migrate.ts
> +
removed refs to cdk bucket

2020-12-04 15:23 UTC, ialford commented on src/honeypot-stack.ts
> +    if (!fs.existsSync(props.appDirectory)) {
Went to AssetHelpers. This was an artifact from before we had that helper.

2020-12-08 14:31 UTC, jgondron commented on test/buzz-pipeline.test.ts
> +    // Like this maybe?
```suggestion
```
Maybe this isn't a maybe anymore? 😺

2020-12-08 14:32 UTC, jgondron commented on test/buzz-pipeline.test.ts
> +    // app.node.setContext('dockerhubCredentialsPath', '/path/to/oauth')
```suggestion
```

2020-12-08 14:32 UTC, jgondron approved these changes

2020-12-08 14:38 UTC, merged